


<div class="row ">
    <div class="col-md-6">
        <form role="form" method="POST" action="">
            <div class="form-group">
                <label class="control-label" for="exampleInputEmail1">User Name</label>
                <input class="form-control" id="email" name="username"
                       placeholder="Enter your username" type="text">
            </div>
            <div class="form-group">
                <label class="control-label" for="password">Password</label>
                <input class="form-control" id="password" name="password"
                       placeholder="Password" type="password">
            </div>
            <div class="form-group">
                <label class="control-label" for="error" style="color:red"><?php
                    if(isset($this->register_error)){
                        echo $this->register_error;
                    }
                ?></label>

            </div>
            <button type="submit" class="btn btn-default">Register</button>
        </form>
    </div>
</div>
</div>