<br /><br />
<div id="view-content">
    <div class="jumbotron">  
        <div class="container">
            <div class="row">
                <h3 class="text-danger">
                    <div class="btn-primary col-md-4">Exam Name:</div>
                    <div class="btn-success col-md-8"><?php echo $this->data['exam_name']; ?></div>

                    <hr>  <hr>
                    <div class="btn-primary col-md-4">Time used(mm:ss):</div>
                    <div class="btn-success col-md-8"><?php echo $this->data['duration']; ?></div>
                    <hr>  <hr>
                    <div class="btn-primary col-md-4">Marks</div>
                    <div class="btn-success col-md-8"><?php echo $this->data['mark']; ?></div>
                    <hr>  <hr>
                    <div class="btn-primary col-md-4">Advice</div>
                    <div class="btn-success col-md-8"><?php echo $this->data['comment']; ?></div>
                </h3>
            </div>

        </div>
    </div>
</div>