<div class="tabbable-panel">
    <div class="tabbable-line">
        <ul class="nav nav-tabs ">
            <li class="active">
                <a href="#basic_info_tab" data-toggle="tab">
                    <h4>Exam Basic Info</h4></a>
            </li>
            <li>
                <a href="#questions_tab" data-toggle="tab">
                    <h4>Exam Questions:</h4> </a>
            </li>
            <li>
                <a href="#analyse_tab" data-toggle="tab">
                    <h4>Analyse Report</h4> </a>
            </li>
           
        </ul>
        <br/>
        <div class="tab-content">
            <div class="tab-pane active" id="basic_info_tab">
               <?php echo $this->render("exam/basic_info_tab.phtml")?>
            </div>
            <!--exam questions-->
            <div class="tab-pane " id="questions_tab">
             <?php echo $this->render("exam/question_tab.phtml")?>
            </div>
            
            <div class="tab-pane" id="analyse_tab">
                <?php echo $this->render("exam/report_tab.phtml")?>
            </div>
          
        </div>
    </div>
</div>
